name: Code check
on:
  - push

jobs:
  analysis:
    name: PHP Code static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer, phpstan, psalm

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: PHPStan
        run: phpstan analyse -c phpstan.neon.dist --error-format=github

      - name: Psalm
        if: ${{ always() }}
        run: psalm --config=psalm.xml --output-format=github

      - name: Psalm security
        if: ${{ always() }}
        run: psalm --config=psalm.xml --output-format=github --taint-analysis
